[pytest]
pythonpath = src
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts =
    --verbose
    --cov=src/models
    --cov=src/repositories
    --cov=src/services
    --cov=src/handlers
    --cov=src/utils
    --cov-report=term-missing
    --cov-report=html
    --cov-fail-under=80
